# Machine Learning Concepts/Glossary

In this markedown we'll explore various concepts and glossary need to understand how ML works.


In [1]:
# Importing packages
from torch import nn

import matplotlib.pyplot as plt
import numpy as np
import torch

### Convolution Layer

In CNNs (Convolutional Neural Networks), this layer applies the convolution operation on the input. The convolution operation involves sliding a small window (referred to as kernel or filter) across the input data and performs dot product and slides with a stride. The output of convolution layer is a feature map.

**Note**: This layer has learnable parameters that are kernel/filter. 

![Convolution layer](https://cdn.prod.website-files.com/614c82ed388d53640613982e/6462188f86bb3724db70a0c5_convolutional%20layer.webp)
**Image Source**: [https://www.superannotate.com/blog/guide-to-convolutional-neural-networks](https://www.superannotate.com/blog/guide-to-convolutional-neural-networks)

Mathematically represented as:

$$y(i, j) = \sum_m \sum_n x(i + m, j + n) \cdot w(m, n) + b$$

Where:
- $x(i, j)$ = input image or feature map
- $w(m, n)$ = filter or kernel (window)
- $y(i, j)$ = convolution layer output
- $i, j$ = position in input feature map
- $m, n$ = positions in kernel or filter
- $b$ = bias

In `nn.Conv2d` the input shape is as follows:

$$X.shape = (N, C_{in}, H_{in}, W_{out})$$

The shape of the Conv2d weight is as follows:

$$Conv2d.weight.shape = (C_{out}, C_{in}, K_h, K_w)$$

The output shape of the Convolution layer is:

$$Convolution.output.shape = (N, C_{out}, H_{out}, W_{out})$$

The height and width of the feature map is computed as follows:

$$H_{out} = \frac{H_{in} - K_h + 2P_h}{S_h} + 1$$

$$W_{out} = \frac{W_{in} - K_w + 2P_w}{S_w} + 1$$

In simple terms:

$$output\_size = \frac{input\_size - kernel\_size + 2 \times padding}{stride} + 1 $$

Where:
- $N$ = No. of samples/batch size
- $C_{out}$ = No. of channels of the convolution layer output
- $C_{in}$ = No. of channels in the input image
- $H_{in}$ = Height of the input image
- $W_{in}$ = Width of the input image
- $H_{out}$ = Height of the output image
- $W_{out}$ = Width of the output image
- $K_h$ = Height of the kernel
- $K_w$ = Width of the kernel
- $S_h, S_w$ = Height and width of the stride
- $P_h, P_w$ = Height and width of the padding

In case of a square kernel: $K_h = K_w$

In [2]:
input_data = torch.rand(size=(5, 5), )

In [3]:
# Let's take the example from this video: https://www.youtube.com/watch?v=sAPg-qaT0b4

# Set the image pixels.
image = torch.tensor([
    [1, 0, 4, 2, 125, 67],
    [8, 2, 5, 4, 34, 12],
    [20, 13, 25, 15, 240, 2],
    [76, 8, 6, 6, 100, 76],
    [34, 66, 134, 223, 201, 3],
    [255, 123, 89, 55, 32, 2]
], dtype=torch.float32)

image = image.reshape(1, 6, 6)

image, image.shape

(tensor([[[  1.,   0.,   4.,   2., 125.,  67.],
          [  8.,   2.,   5.,   4.,  34.,  12.],
          [ 20.,  13.,  25.,  15., 240.,   2.],
          [ 76.,   8.,   6.,   6., 100.,  76.],
          [ 34.,  66., 134., 223., 201.,   3.],
          [255., 123.,  89.,  55.,  32.,   2.]]]),
 torch.Size([1, 6, 6]))

In [4]:
# Initialize the custom kernel.
kernel = torch.tensor([
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1,]
], dtype=torch.float32)

kernel, kernel.shape

(tensor([[1., 2., 1.],
         [2., 4., 2.],
         [1., 2., 1.]]),
 torch.Size([3, 3]))

In [5]:
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(3, 3), stride=1, padding=0)

# Setting the custom kernel.
with torch.no_grad(): # disable gradient tracking
    conv_layer.weight = nn.Parameter(kernel.reshape(1, 1, 3, 3))

conv_layer, conv_layer.weight

(Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1)),
 Parameter containing:
 tensor([[[[1., 2., 1.],
           [2., 4., 2.],
           [1., 2., 1.]]]], requires_grad=True))

In [6]:
output = conv_layer(image).ceil()

output, output.shape

(tensor([[[ 110.,  120.,  522.,  984.],
          [ 257.,  198.,  755., 1360.],
          [ 567.,  687., 1312., 1689.],
          [1288., 1496., 1911., 1659.]]], grad_fn=<CeilBackward0>),
 torch.Size([1, 4, 4]))

Output shape is computed as follows:

$$ H_{out} = W_{out} = \frac{6 - 3 + 2(1)}{1} + 1 = 6$$

Output shape: $(C_{out}, H_{out}, W_{out})$ = $(1, 6, 6)$


### Max/Average Pooling Layer

Pooling is the process of reducing the size of the input image or feature map by summarizing regions. This process is often also referred to as down sampling.

In max pooling the maximum value is selected from the grid of pool size whereas in average pooling we take the average of all the values in the grid.

**Note**: This layer does not contain any learnable parameters. 


In [7]:
# Let's take the same example from this video: https://www.youtube.com/watch?v=o_DJ-FO6dw0

# Max Pooling
max_pool = nn.MaxPool2d(kernel_size=(2, 2), padding=0, stride=2)(output)
max_pool, max_pool.shape

(tensor([[[ 257., 1360.],
          [1496., 1911.]]], grad_fn=<MaxPool2DWithIndicesBackward0>),
 torch.Size([1, 2, 2]))

In [8]:
# Average Pooling
avg_pool = nn.AvgPool2d(kernel_size=(2, 2), padding=0, stride=2)(output)
avg_pool, avg_pool.shape

(tensor([[[ 171.2500,  905.2500],
          [1009.5000, 1642.7500]]], grad_fn=<AvgPool2DBackward0>),
 torch.Size([1, 2, 2]))

Output shape is computed as follows:

$$ H_{out} = W_{out} = \frac{6 - 3 + 2(0)}{2} + 1 = 2$$

Output shape: $(C_{out}, H_{out}, W_{out})$ = $(1, 2, 2)$



### Batch Normalization


#### Batch Norm (`nn.BatchNorm1d`)
Normalizes the input data across the batch dimension to stabilize training and accelerate convergence. It is done across the batch.

In general the shape of X is $(batch\_size, num\_features, sequence\_length)$

**Calculate Mean ($\mu$):**

$$\mu = \frac{1}{N} \sum_{i = 0}^{N} x_i$$

**Calculate variance ($\sigma$):**

$$\sigma^2 = \frac{1}{N} \sum_{i = 0}^{N}(x_i - \mu)^2$$

**Batch1d Normalization:**

$$\hat{x_i} = \frac{x_i - \mu}{\sqrt{\sigma^2 + \epsilon}}$$

**Learnable Affine Transformation:**

$$y_i = \gamma \hat{x_i} + \beta$$

Where:
- $\gamma$ = Learnable **scale** parameter (Default: 1)
- $\beta$ - Learnable **shift** parameter (Default: 0)

This normalization is used in deep learning models that require batch-based training in CNNs and MLPs.

Learnable parametes are applied per feature.

In [9]:
# Epsilon
e = 1e-5

x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32)

x, x.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.Size([2, 3]))

In [10]:
mean = x.mean(dim=0)
mean

tensor([2.5000, 3.5000, 4.5000])

In [11]:
var = x.var(dim=0, correction=0) # Set the delta*N = 0
var

tensor([2.2500, 2.2500, 2.2500])

In [12]:
(x - mean) / torch.sqrt(var + e)

tensor([[-1.0000, -1.0000, -1.0000],
        [ 1.0000,  1.0000,  1.0000]])

In [13]:
# Even if you set affine=False the result will be same because this layer hasn't
# learned the gamma and beta and defaults to 1 and 0
nn.BatchNorm1d(3, affine=True)(x)

tensor([[-1.0000, -1.0000, -1.0000],
        [ 1.0000,  1.0000,  1.0000]], grad_fn=<NativeBatchNormBackward0>)

### Layer Normalization (`nn.LayerNorm`)

Normalization is done across the feature dimension.

Used in Recurrent Neural Networks (RNNs), Transformers and situations where the batch size is small or variable.

Learnable parametes are applied per feature.

In [14]:
var = x.var(dim = 1, correction=0, keepdim=True)
var

tensor([[0.6667],
        [0.6667]])

In [15]:
mean = x.mean(dim=1, keepdim=True)
mean

tensor([[2.],
        [5.]])

In [16]:
(x - mean) / torch.sqrt(var + e)

tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]])

In [17]:
nn.LayerNorm(3, elementwise_affine=True)(x)

tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]], grad_fn=<NativeLayerNormBackward0>)

### BatchNorm2d

It normalizes 2-dimensional data across the batch dimension especially for convolutional layers. It is similar to BatchNorm2d but it computes the mean and variance over batch_size, height, and width but not the channel.

In [18]:
x_new = torch.stack([x, x, x], dim=0)
x_new = torch.stack((x_new, x_new), dim=0)


x_new, x_new.shape

(tensor([[[[1., 2., 3.],
           [4., 5., 6.]],
 
          [[1., 2., 3.],
           [4., 5., 6.]],
 
          [[1., 2., 3.],
           [4., 5., 6.]]],
 
 
         [[[1., 2., 3.],
           [4., 5., 6.]],
 
          [[1., 2., 3.],
           [4., 5., 6.]],
 
          [[1., 2., 3.],
           [4., 5., 6.]]]]),
 torch.Size([2, 3, 2, 3]))

In [19]:
mean = x_new.mean(dim=(0, 2, 3), keepdim=True)
print(f"Mean: {mean}")

var = x_new.var(dim=(0, 2, 3), keepdim=True, correction=0)
print(f"Variance: {var}")

Mean: tensor([[[[3.5000]],

         [[3.5000]],

         [[3.5000]]]])
Variance: tensor([[[[2.9167]],

         [[2.9167]],

         [[2.9167]]]])


In [20]:
(x_new - mean) / torch.sqrt(var + e)

tensor([[[[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]]],


        [[[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]]]])

In [21]:
nn.BatchNorm2d(3)(x_new)

tensor([[[[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]]],


        [[[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]],

         [[-1.4638, -0.8783, -0.2928],
          [ 0.2928,  0.8783,  1.4638]]]], grad_fn=<NativeBatchNormBackward0>)

### Residual Networks

Residual Network ([ResNet](https://en.wikipedia.org/wiki/Residual_neural_network)) is a type of neural network where the key ideas is the **residual connection**, that helps in training very deep networks by mitigating the vanishing/exploding gradient problem.

As the depth of the network increases the training becomes difficult because of the **vanishing** (small gradients - network stops learning)/**exploding** (large gradients - instability and poor convergence) gradients. The solution is to use **skip (shortcut) connections**, which allow gradients to bypass multiple layers, making backpropagation more effective.

<div style="text-align: center;">
<img src="https://upload.wikimedia.org/wikipedia/commons/b/ba/ResBlock.png" alt="Alt text" width="734" />
</div>

$$\text{Residual Block with Skip connection (Image Source: Wikipedia)}$$

Instead of learning the desired output $H(x)$. ResNets learn a "residual" function $F(x)$

$$F(x) = H(x) - x$$

$$H(x) = F(x) + x$$

Where,
- $x$ = input
- $F(x)$ = output of the residual block
- $H(x)$ = desired output