# Basics of PyTorch - Tensors
### Date: 02/19/2025
### by Malik N. Mohammed

## Objectives
- Understand tensors in PyTorch
- Understand all tensor operations
- Build a simple model


In [5]:
import numpy as np
import torch


In [2]:
# Get the current accelerator or cpu
device = 'cpu'

if torch.accelerator.is_available():
  device = torch.accelerator.current_accelerator()

device

device(type='cuda')

### Initializing a Tensor
Tensors are special data structrues just like arrays and matrices that are generally used to store numerical values for faster computation

In [4]:
data = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]

data_t = torch.tensor(data)
data_t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# Tensor from NumPy array
data_np = np.array(data)
data_t = torch.from_numpy(data_np)
data_t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# tensor with 1s
ones = torch.ones(size=(4, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [11]:
# tensor with 0s
zeros = torch.zeros(size=(4, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [14]:
# tensor with random values
random = torch.rand(size=(4, 6))
random

tensor([[0.9944, 0.4805, 0.5116, 0.1366, 0.4135, 0.4256],
        [0.6581, 0.1824, 0.8805, 0.3832, 0.1053, 0.1995],
        [0.6167, 0.2553, 0.4288, 0.5260, 0.8189, 0.5808],
        [0.3271, 0.8147, 0.1858, 0.2928, 0.9203, 0.2166]])

In [18]:
# creating tensor with the properties of another tensor

# creates the random tensor with the properties of ones. Other functions: ones_like(), zeroe_
rand_like = torch.rand_like(ones)
rand_like

tensor([[0.9466, 0.5263, 0.4256, 0.8970, 0.4069],
        [0.5686, 0.9627, 0.8903, 0.2643, 0.6880],
        [0.3930, 0.8626, 0.4903, 0.8606, 0.8294],
        [0.2119, 0.7215, 0.1460, 0.0614, 0.9685]])

### Tensor Attributes
Tensor has 3 main attributes: shape, datatype, and device on which the tensor is stored.

In [23]:
data = torch.rand(4, 7)

print(f'Tensor shape: {data.shape}')
print(f'Tensor datatype: {data.dtype}')
print(f'Device where the tensor is stored: {data.device}')

# Moving data to accelerator/gpu if available
print('Moving data to accelerator...')
data = data.to(device)

print(f'Device where the tensor is stored: {data.device}')

Tensor shape: torch.Size([4, 7])
Tensor datatype: torch.float32
Device where the tensor is stored: cpu
Moving data to device...
Device where the tensor is stored: cuda:0


### Tensor Operations
We can perform many tensor operation and some of them are: Matrix-multiplication, dot-product, element-wise product, and more

In [26]:
# Slicing, indexing and updating values
tensor = torch.rand(size=(4, 5))
tensor

tensor([[0.7672, 0.4193, 0.1294, 0.1670, 0.9536],
        [0.8249, 0.5730, 0.4311, 0.6378, 0.2006],
        [0.3999, 0.0119, 0.0198, 0.3398, 0.1882],
        [0.1178, 0.0220, 0.1842, 0.0081, 0.8404]])

In [28]:
# Slicing
tensor[:, :2] # All rows and first two columns

tensor([[0.7672, 0.4193],
        [0.8249, 0.5730],
        [0.3999, 0.0119],
        [0.1178, 0.0220]])

In [32]:
tensor[:, -1] # tensor[..., -1] - select last column of the tensor

tensor([0.9536, 0.2006, 0.1882, 0.8404])

In [34]:
# Update the values of the last column's first 3 rows
tensor[:3, -1] = 0
tensor

tensor([[0.7672, 0.4193, 0.1294, 0.1670, 0.0000],
        [0.8249, 0.5730, 0.4311, 0.6378, 0.0000],
        [0.3999, 0.0119, 0.0198, 0.3398, 0.0000],
        [0.1178, 0.0220, 0.1842, 0.0081, 0.8404]])

#### Joining Tensors

In [45]:
t1 = torch.rand(2, 3, 4)
t1

tensor([[[0.7253, 0.4390, 0.1694, 0.1663],
         [0.7610, 0.4547, 0.9777, 0.4407],
         [0.0190, 0.2334, 0.3774, 0.3818]],

        [[0.3977, 0.4764, 0.2618, 0.5655],
         [0.7888, 0.4425, 0.7957, 0.9975],
         [0.4069, 0.2623, 0.6606, 0.6108]]])

In [48]:
t2 = torch.rand(2, 2, 4)
t2

tensor([[[0.9549, 0.7694, 0.6740, 0.6639],
         [0.4950, 0.0730, 0.3828, 0.9687]],

        [[0.2456, 0.9887, 0.0289, 0.1278],
         [0.1235, 0.1288, 0.5963, 0.1524]]])

In [51]:
# Concatenates tensors along a given dimension (0-indexed).
torch.cat((t1, t2), dim=1)

tensor([[[0.7253, 0.4390, 0.1694, 0.1663],
         [0.7610, 0.4547, 0.9777, 0.4407],
         [0.0190, 0.2334, 0.3774, 0.3818],
         [0.9549, 0.7694, 0.6740, 0.6639],
         [0.4950, 0.0730, 0.3828, 0.9687]],

        [[0.3977, 0.4764, 0.2618, 0.5655],
         [0.7888, 0.4425, 0.7957, 0.9975],
         [0.4069, 0.2623, 0.6606, 0.6108],
         [0.2456, 0.9887, 0.0289, 0.1278],
         [0.1235, 0.1288, 0.5963, 0.1524]]])

In [57]:
x = torch.rand(size=(2, 3))
x

tensor([[0.6407, 0.3200, 0.0573],
        [0.9971, 0.9268, 0.8519]])

In [58]:
# Stacks the tensors along a given index (adds new dimension)
torch.stack((x, x), dim=0)

tensor([[[0.6407, 0.3200, 0.0573],
         [0.9971, 0.9268, 0.8519]],

        [[0.6407, 0.3200, 0.0573],
         [0.9971, 0.9268, 0.8519]]])

In [62]:
torch.stack((x, x), dim=-1)

tensor([[[0.6407, 0.6407],
         [0.3200, 0.3200],
         [0.0573, 0.0573]],

        [[0.9971, 0.9971],
         [0.9268, 0.9268],
         [0.8519, 0.8519]]])

#### Tensor Arithematic

In [66]:
tensor = torch.rand(size=(3, 4)).to(device)
tensor

tensor([[0.4011, 0.3317, 0.6553, 0.2672],
        [0.8319, 0.0845, 0.4344, 0.9573],
        [0.7267, 0.0357, 0.7715, 0.8907]], device='cuda:0')

In [67]:
# Matrix Multiplication

y1 = tensor @ tensor.T # (3, 4) * (4, 3) => (3, 3)
y1

tensor([[0.7717, 0.9021, 1.0468],
        [0.9021, 1.8042, 1.7953],
        [1.0468, 1.7953, 1.9179]], device='cuda:0')

In [69]:
# another way
y2 = torch.matmul(tensor, tensor.T)
y2

tensor([[0.7717, 0.9021, 1.0468],
        [0.9021, 1.8042, 1.7953],
        [1.0468, 1.7953, 1.9179]], device='cuda:0')

In [72]:
# Element-wise product
z1 = tensor * tensor # or, tensor.mul(tensor)
z1

tensor([[0.1608, 0.1101, 0.4294, 0.0714],
        [0.6920, 0.0071, 0.1887, 0.9163],
        [0.5282, 0.0013, 0.5952, 0.7933]], device='cuda:0')

In [73]:
tensor.mul(tensor)

tensor([[0.1608, 0.1101, 0.4294, 0.0714],
        [0.6920, 0.0071, 0.1887, 0.9163],
        [0.5282, 0.0013, 0.5952, 0.7933]], device='cuda:0')

In [81]:
# Tensor addition.
t = torch.ones(size=(4, 4))
t[:, 2] = 2
t.add(5) # or, 5 + t

tensor([[6., 6., 7., 6.],
        [6., 6., 7., 6.],
        [6., 6., 7., 6.],
        [6., 6., 7., 6.]])

In [86]:
# Sum of all the elements of the tensor as a single-value
t.add(5).sum().item()

100.0

In [100]:
# Dot product (a, b)
#   result = sum(ai * bi)
t1 = torch.ones(3)
t1

tensor([1., 1., 1.])

In [98]:
t2 = torch.ones(3)
t2

tensor([1., 1., 1.])

In [101]:
t1.dot(t2) # Returns a scalar value.

tensor(3.)

In [102]:
a = torch.tensor([1, 2, 3])  # Shape: (3,)
b = torch.tensor([4, 5, 6])  # Shape: (3,)

outer = torch.ger(a, b)  # Equivalent to a[:, None] * b[None, :]
print(outer)


tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


In [114]:
# Bridge with NumPy

n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [115]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [117]:
# Change in NumPy array reflects on Tensor.
np.add(n, 2, out=n)
t

tensor([5., 5., 5., 5., 5.], dtype=torch.float64)

In [118]:
# Get the numpy from tensor
t.numpy()

array([5., 5., 5., 5., 5.])